### ISSUE TITLE
Make search bar and description toggle look nice

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#10]
http://mozilla.github.io/mozfest-schedule-app/#_show-all

![screen shot 2015-10-28 at 6 56 53 pm](https://cloud.githubusercontent.com/assets/2896608/10808188/c8e5c77a-7da5-11e5-8536-bddb9b3ebd92.png)

/cc @cassiemc

**Comment by diptajbasu** [comment]
Hi folks,

I had some ideas for this issue, I hope they are helpful =) I'm sending in a PR for the search bar. I also thought a switch might work for the description toggle, similar to this one: http://codepen.io/diptajbasu/full/zvaydY/

Cheers!

![mozfest_switch](https://cloud.githubusercontent.com/assets/7990216/10866979/244f4320-8021-11e5-8b7c-84730942d74b.png)

![mozfest_searchbar](https://cloud.githubusercontent.com/assets/7990216/10866965/2d87d430-8020-11e5-81f8-096be65ba312.png)

**Comment by cassiemc** [comment]
Toggle would be great, thanks @diptajbasu! 
I also mentioned this in #49 so clearly we're on the right track. Would just make it pink instead of green.

**Comment by mmmavis** [comment]
Closing this now. Marked this ticket as "MozFest 2015" in case we want to revisit again.
