### ISSUE TITLE
Make the text in the listings pages selectable 

### ISSUE THREAD

**Issue by davidascher** [mozilla/schedule-app-core#101]
e.g. https://app.mozillafestival.org/#_show-saturday

I'd like to be able to copy & paste the extract to send in an email.

**Comment by ryanpitts** [comment]
This is an interesting usability question, I think. There's a tension between making the "cards" easily tappable on mobile devices, which leads the app toward making the entire session item a touch/click target, and having the text be easily selectable. (You can select text on these pages by starting your click-and-drag just above or below the card, fwiw, but maybe that's not a complete or immediately intuitive solution.)

What device are you using when running into this @davidascher ?

**Comment by davidascher** [comment]
Desktop browser.

On desktop I'm not sure there's a lot of value in deferring the detailed
view to the per event view.

One of the challenges is the titles are usually cryptic, which means that
it's hard to scan for interesting sessions without drilling down.

**Comment by mmmavis** [comment]
I believe this has been fixed in [PR #185](https://github.com/mozilla/schedule-app-core/pull/185) by making only the session title hyperlinked. See http://mozilla.github.io/mofo-allhands/2016-london/ 😄
