### ISSUE TITLE
Make detailed description of the talk available in summary views

### ISSUE THREAD

**Issue by davidascher** [mozilla/schedule-app-core#102]
ideally through a toggle, so that the user can find out more about a session w/o going to a new page (which is a pain on the crappy local wifi).  A toggle "show more/less" would do fine.

**Comment by mmmavis** [comment]
This is a single page app. [sessions.json](https://github.com/mozilla/mozfest-schedule-app/blob/gh-pages/sessions.json) is loaded on the first page load and any subsequent view changes is just feeding data into different js templates.

I think we can show description in summary view but that'll be even more of scrolling for the viewer? :confounded:

**Comment by kristinashu** [comment]
Once the landing page is loaded all the other pages are viewable, even if the user is offline. Closing this since we're trying to keep changes to a minimum.
