### ISSUE TITLE
Determine if session details could be clickable

### ISSUE THREAD

**Issue by thornet** [mozilla/schedule-app-core#14]
If you're at any one session, there's a number of session details that would be great to click on and see all other sessions that have the information. 

For example: 

If I'm looking at this session: http://mozilla.github.io/mozfest-schedule-app/#_session-410

and I click on the space info: "youthZone - Through the lens of youths" --> it'll take me to all sessions in the youthzone space. 

Same if I click on the pathway info --> shows all sessions in that pathway
or the time block --> all sessions in that time block 
and facilitator --> all sessions by that facilitator

Don't know if that's feasible cc @mmmavis @ryanpitts or part of the wishlist for next year (#7)

**Comment by ryanpitts** [comment]
100% agree that it should be our goal to make _at least_ the pathways clickable like this. Time and facilitator would be nice as well, but those are at least able to be surfaced in other ways for now.

I was planning to look into this today, hopefully can figure something out.

**Comment by thornet** [comment]
Perfect! Thank you.

**Comment by ryanpitts** [comment]
Space and Pathway are now clickable from session detail views. It's coming together!

Example: http://mozilla.github.io/mozfest-schedule-app/#_session-511

**Comment by thornet** [comment]
Love it!

On Fri, Oct 30, 2015 at 12:04 AM, Ryan Pitts <notifications@github.com>
wrote:

> Space and Pathway are now clickable from session detail views. It's coming
> together!
>
> Example: http://mozilla.github.io/mozfest-schedule-app/#_session-511
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozfest-schedule-app/issues/14#issuecomment-152361278>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org
