### ISSUE TITLE
Remove hardcoded schedule block container <div>s from index.html

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#158]
Remove hardcoded schedule block container `<div>`s like [these](https://github.com/mozilla/schedule-app-core/blob/develop/index.html#L50-L78)  from `index.html` so devs won't have to edit this file every time a change to schedule block is introduced in the data source.

**Comment by mmmavis** [comment]
I think I'm gonna change this ticket a bit. 

The `index.html` originally has lists of predefined & hardcoded schedule blocks like [these](https://github.com/mozilla/schedule-app-core/blob/develop/index.html#L50-L78) as well as templates like [this](https://github.com/mozilla/schedule-app-core/blob/develop/index.html#L114-L140) that are being used in different scenarios and views. My original cleanup plan was to remove both of them from `index.html` and let the script handles everything instead. Now I think of it, I think it definitely makes sense that we remove the hardcoded blocks so a dev doesn't have to edit `index.html` every time a new schedule block is added to the data source (which has been taken care of [in this commit](https://github.com/mmmavis/schedule-app-core/commit/48ecb7d5607e970eafd53e01f2c39f71006cbca6#diff-eacf331f0ffc35d4b482f1d15a887d3bL50)).  Regarding the template code piece I think we should probably leave them in `index.html` to make our script clean as using jQuery to properly render these HTML DOM elements with many condition checks will be very tedious and complicated.

What do you think @xmatthewx ? Leaving the templates in `index.html` on the other hand means we need to communicate to the script users that they'll need to use the templates we provided. Maybe we can provide a  `example-index.html` for people to use?

**Comment by xmatthewx** [comment]
This sounds very logical. You're pulling out things that are event specific and might change during event planning (session times and length), but leaving in things that are structural and unlikely to change (sessions have attributes: start time, category). Including an example-index.html is excellent. Makes it easy, flexible, and obvious that someone can make changes there.

**Comment by mmmavis** [comment]
yay, glad to hear I got the +1 from you @xmatthewx :+1: 

let me edit this ticket a bit then!

**Comment by mmmavis** [comment]
fixed in [PR #168](https://github.com/mozilla/schedule-app-core/pull/168)
