### ISSUE TITLE
Repo name for London all-hands schedule

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#180]
We would like to create a demo schedule app with some dummy data so that we can present it to Matt (or/and people on MoFo's all-hands planning team) and talk about the possibilities of using this app for the upcoming London all-hands.

The app and repo will live on Github, under the organization "mozilla" (not "MozillaFoundation"). This means that the repo name will be part of the URL to the app.
e.g.,
if the repo name is `yay-awesome-schedule` 
the URL to the app will be http://mozilla.github.io/yay-awesome-schedule

@xmatthewx and I brainstormed a few, but we would love to know your suggestion and input as well :wink: @ldecoursy @hannahkane 

Here's what we have

- mofo-london-2016
- mofo-allhands
- foundation-2016-allhands
- mofo-allhands-schedule

**Comment by mmmavis** [comment]
I would vote for *not* including year and event specific terms in the repo (e.g., 2016, London etc). That way we don't have to create a new repo for every single upcoming all-hands.  One repo for all. Yay!

**Comment by hannahkane** [comment]
@ldecoursy is on PTO until next week. If you need an answer before then, I'd go with mofo-allhands for the reasons you mention + keeping it short and sweet. :)

**Comment by xmatthewx** [comment]
We can pick a name now and then change it after we have input from Laine. 

At first, I thought we should include the year so we could look at prior all-hand schedules and find the connected documentation. But now I wonder if we could `category` to mark the year/location, and just use tags for marking teams/topics.

**Comment by mmmavis** [comment]
@xmatthewx 

> But now I wonder if we could category to mark the year/location, and just use tags for marking teams/topics.

I like this idea! :+1:

**Comment by hannahkane** [comment]
Sorry, what is the category?

**Comment by mmmavis** [comment]
`category` and `tag` are the 2 generic terms I came up with (open to other suggestions too)
- a session can only belong to ONE `category` (like last year's MozFest's "space")
- a session can have multiple `tags` (like last year's MozFest's "pathways")

**Comment by xmatthewx** [comment]
Exactly. Since mofo all-hands are much simpler than mozfest, we could use the same app for multiple all hands, with each session categorized `June 2016`, `Dec 2016`, `June 2017`, etc. And then use tags to mark `Leadership`, `Advocacy`, `Production`, etc.

**Comment by hannahkane** [comment]
Oooh...I like it!

**Comment by mmmavis** [comment]
sorry people now I have a second thought (apologies if my comment below gets technical)

How the app currently works - on a "category" page (e.g., https://app.mozillafestival.org/#_space-journalism from last year's MozFest) we filter **all** sessions by that specific category name and display the filtered list on the page. 

If we decide to load another all-hands sessions within the same app... technically it's doable but this will require some adjustment to the app code as the app assumes all sessions it loads belong to the same event. 

Another possible approach is to have each event app live on different path on http://mozilla.github.io/mofo-schedule
e.g., 
- http://mozilla.github.io/mofo-schedule/2016-london
- http://mozilla.github.io/mofo-schedule/2016-hawaii

We can just link out to any past event app instead of trying to load past event sessions on the same app. Another good thing about this is that bookmarked links can be preserved and we don't have to worry about same `id` being used across multiple events.

**Comment by mmmavis** [comment]
:tada: Got a +1 from @xmatthewx on my suggestion above. Will go ahead and make the change.  Note that we should redirect the root URL http://mozilla.github.io/mofo-allhands/ to http://mozilla.github.io/mofo-allhands/2016-london

**Comment by ldecoursy** [comment]
We already started a repo for planning and organizing sessions here: https://github.com/MozillaFoundation/MoFoLondon/issues Hoping its OK for us to continue using that and then port over final sessions into the repo you're suggesting above.

**Comment by mmmavis** [comment]
hey @ldecoursy , you can definitely continue using the MoFoLondon repo for session planning. The repo we are referring to in this ticket is where the app and code should live (sorry for the confusion).

And... I just transferred the app repo from mine to Mozilla: https://github.com/mozilla/mofo-allhands :smile: :tada:
