### ISSUE TITLE
Quick design audit on app UI / UX

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#181]
Hey @vazquez ,

@xmatthewx and I mentioned about this earlier and we hope you can lend a hand here :ok_hand:  Can you do a quick design audit on the current UI / UX: http://mmmavis.github.io/mofo-allhands/ ? Let's stick with small tweaks for now as I think we don't have the time luxury to introduce big changes to the codebase. :grin: 

FYI, @xmatthewx and I jot down a few suggestion. Please feel free to edit them! :smile_cat: 
- nav tabs
  - 4 days (excluding Monday) + favs + all
  - search icon instead of "all". heart and search as half width item
  - or other ways to make that nav bar more mobile friendly
- add padding to the search box on the "All" tab
- session title as link instead of whole card
- single session view with back button, minimal header

**Comment by vazquez** [comment]
How about these small tweaks?

- Change colours of dropdown icons to maroon
- `text-transform: capitalize` all session fields (Title, Time, Location, Space)
- Redesign Tags Page so that tags don't look like sessions, it is visually confusing (make them pills or tags)
- Add animation when heart is clicked
- I really like the idea to make the 'All' button a search button instead. We can also do some UI tweaks to the search box when we get this functionality working.

**Comment by xmatthewx** [comment]
#### replies

> - Change colours of dropdown icons to maroon

Caret to expand/collapse afternoon etc

> - `text-transform: capitalize` all session fields (Title, Time, Location, Space)

All caps all the time? Seems like a lot for location. If we do go all caps on title, we'll want to change weight and maybe letter spacing.

> - Redesign Tags Page so that tags don't look like sessions, it is visually confusing (make them pills or tags)

Good point. Wondering how this could be done in a simple way.

> - Add animation when heart is clicked

Scope creep alert 😄 

> - I really like the idea to make the 'All' button a search button instead. We can also do some UI tweaks to the search box when we get this functionality working.

Search is already functional. We could add a dismiss (x) icon to cancel search term. Field needs padding. We might want to show no sessions when input value is empty.

#### more notes

 - The phrase "Hide all sessions" should be rephrased, removed, or clarified. Shrink time blocks?  I question whether we need this and recommend we remove it. 
 - Favs
  - This section has way too much default content. Saturday registration? That's not my favorite. 
  - I recommend that we change this paradigm. We could heart a few things by default, like Science Fair. But give people the freedom to un-heart them. 
  - This sentence is unclear: "Favorite sessions to store a list on this device". This section could use a header `FAVORITES`. Under that something like: "Tap the hearts to add favorites to your list here."

**Comment by mmmavis** [comment]
@xmatthewx I think `text-transform: capitalize` will just cap the first letter of the entire string. (vs `text-transform: uppercase` will all cap everything) :wink:

**Comment by mmmavis** [comment]
> The phrase "Hide all sessions" should be rephrased, removed, or clarified. Shrink time blocks? I question whether we need this and recommend we remove it. 

This is because we allow users to search words in session description. If we still want to keep this feature then I'll vote for rephrase "Hide all sessions"

**Comment by mmmavis** [comment]
@vazquez @xmatthewx 

What do you think to move the big app headers to the nav bar? I feel this info could appear more subtle than being in big fat headers that show up on every view?

<img width="680" alt="screen shot 2016-04-28 at 2 42 51 pm" src="https://cloud.githubusercontent.com/assets/2896608/14902403/8de1042a-0d4f-11e6-844c-91d99d1c5231.png">

**Comment by xmatthewx** [comment]
Agreed. A more minimal header would be nice.

**Comment by mmmavis** [comment]
some tweaks have been taken care of in [PR #185](https://github.com/mozilla/schedule-app-core/pull/185)
see result here: http://mmmavis.github.io/mofo-allhands/

One thing that worries me is that changes in the template code in `index.html` and `schedule.js` on this repo will break apps that use them as dependency... I had to update `index.html` on each of the apps below
- http://mmmavis.github.io/mofo-allhands
- http://mozilla.github.io/mozfest-schedule-app/
- http://mmmavis.github.io/iron-chef-schedule-app/

so that they won't break due to the changes in https://mozilla.github.io/schedule-app-core/js/schedule.js that they link to...

This can become quite cumbersome but I'm not sure how to solve this :confused:

**Comment by xmatthewx** [comment]
> This process can become quite cumbersome but I'm not sure how to solve this :confused: Should we start versioning schedule.js ?

Let's discuss during today's stand. Ideally core will stabilize and anything that isn't truly core can be lifted to the customizable layer. And, versioning now could save a heap of trouble later. Hmm...

**Comment by xmatthewx** [comment]
I think we can close this now. Remaining items filed separately.
