### ISSUE TITLE
Improve the look of ti.to

### ISSUE THREAD

**Issue by vazquez** [mozilla/schedule-app-core#182]
I want to find out how much flexibility ti.to gives us to modify the look of the registration page: https://ti.to/Mozilla/mozfest-2016. 

@mmmavis, do you know how I can access the admin section of ti.to to see/make changes?

**Comment by xmatthewx** [comment]
Cool. Should this ticket be in the mozfest site repo?

**Comment by vazquez** [comment]
Gah, sorry. Repo confusion.
