### ISSUE TITLE
Auto link to Etherpad

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#183]
For London all-hands, we will test a prototype to learn whether or not documentation anchored to an event schedule is a good idea. Find the pain points, opportunities, etc. 

To test this, we will link each session to an etherpad. 
 - unify them with a prefix

In the spreadsheet, we can generate a slug based on the title. Admins could always add a specific slug if they need to, or we could just lock that column. In the app we can create the full link.

Let's discuss!!

cc @mmmavis

**Comment by mmmavis** [comment]
@xmatthewx thanks for adding the slugify functionality to the spreadsheet - it works great!

I'm thinking if we should autogenerate the slug for once only. In other words, even if session name is changed we won't lose the link to the original Etherpad which might already have content filled in it. But... I'm not sure how likely/often a session name will be altered. As long as the spreadsheet editors are aware of the linkage bwtween session name and the Etherpad link, I think we're good! :sunflower:

**Comment by xmatthewx** [comment]
I hear that. It'll take some wrangling of the editors.  

A few options:
 1. link entered manually by planner
 1. link generated by spreadsheet, modified by planner when needed
 1. link generated by app based on session ID instead of title

1 or 2 works. 3 is probably a bad idea.

**Comment by mmmavis** [comment]
is it possible to do something like...
```
if etherpad_slug is empty
  autogenerate slug based on session name
else
  do nothing
```
btw, I added a button on the allhands app http://mmmavis.github.io/mofo-allhands/#_session-1 :smile_cat:

**Comment by xmatthewx** [comment]
Probably so. Make a hidden column that you use for the app. That column can either duplicate the URL column if it's filled in, or build it if not (using function there currently). I don't know the sheets function for the first part, but it probably exists.

**Comment by xmatthewx** [comment]
Button is awesome!! Excited you landed this so quickly.

**Comment by xmatthewx** [comment]
Done!
