### ISSUE TITLE
Consider include font-awesome as css dependency

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#184]

**Comment by xmatthewx** [comment]
Hmmm. Do we have a lot of icons?

**Comment by mmmavis** [comment]
Around 10 I think.

- font-awesome ones:  dropdown arrow * 2, hollow heart *1, filled heart *1, search icon * 1
- icons in a session card were designed by a contractor on MozFest last year: https://github.com/mozilla/schedule-app-core/tree/gh-pages/img (I just saw the heart SVG files. I can replace fontawesome with these SVG instead)

**Comment by xmatthewx** [comment]
It adds up. Whatever you think is easiest and most efficuent. Works for me.

**Comment by kristinashu** [comment]
What design needs to be done for this?

**Comment by mmmavis** [comment]
We are already using font-awesome! Closing this ticket now!
