### ISSUE TITLE
Decide about automatic updates from spreadsheet to app

### ISSUE THREAD

**Issue by thornet** [mozilla/schedule-app-core#19]
I suggest we determine how we update the app. My suggestion: 

* from now - next Thursday (Nov. 5): set up a cron job that updates from the spreadsheet to app every 15min. It'd be great for wranglers to readily see the updates from their spreadsheet edits into the app. 
* Late on Thursday - Mozfest weekend: we lock the spreadsheet so it can only be edited by core team. Set up either a very frequent cron job or super simple way for core team members to push an update to the app. 

@mmmavis @ryanpitts what do you think?

**Comment by ryanpitts** [comment]
personally, :+1: to setting up a regular cron for now, :+1: to "super simple way for core team members to push an update" on MozFest weekend. (Pretty sure this is how @flamingspaz is thinking, but maybe he can weigh in with what that might look like.

**Comment by mmmavis** [comment]
same, +1 on both!

I'll need a hand to have that cron job setup though... maybe @flamingspaz can provide some guidance? :smile:

**Comment by flamingspaz** [comment]
No need to worry about the cron, that'll get handled by jenkins.

For "super simple way", We have an IRC bot that can start an update, and there's also a URL you can use to trigger it which should work for integrating into something like slack.

**Comment by mmmavis** [comment]
@flamingspaz just to double check - so the cron job is set to push the updated sessions.json to `gh-pages` AND `master` every 15 min???

**Comment by flamingspaz** [comment]
Just gh-pages. Ryan and myself decided it was best to only push to one branch to avoid merge conflicts.

**Comment by mmmavis** [comment]
Cool!  For clarification - if there are UI changes or data changes that we want to push to production we'll have to manually do that merge & push to `master` ?

**Comment by mmmavis** [comment]
Also @flamingspaz , the team was wondering if there's a way for them to update the Schedule app data without relying on the cron job.  (other than asking devs to run the Python script from their machine)

**Comment by flamingspaz** [comment]
> Cool! For clarification - if there are UI changes or data changes that we want to push to production we'll have to manually do that merge & push to master ?

Yep. We could change the script to commit schedule changes to master a little later when there are less changes if that works better.

> Also @flamingspaz , the team was wondering if there's a way for them to update the Schedule app data without relying on the cron job. (other than asking devs to run the Python script from their machine)

Can be triggered via IRC (recommended) or through the jenkins web interface. Maybe we could meet up real quick tomorrow to find out which works best for them and show them how to do it?

**Comment by mmmavis** [comment]
@flamingspaz sure sure are you gonna be at MozFest too? :smile:

**Comment by flamingspaz** [comment]
Yep, will be there from about 1pm 😄

**Comment by mmmavis** [comment]
Closing this ticket now. Thanks again team!
