### ISSUE TITLE
Optimize App Header

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#191]
Header should be made more app like and more awesome. Header might also be minified on scroll or on views that aren't the landing page. This is worth a few design options before we build it.

**Comment by vazquez** [comment]
Here's an idea: https://invis.io/K774WYC4B#/155167007_Nav

**Comment by xmatthewx** [comment]
Really nice work and quick by @vazquez. A few adjustments to make, but worth implementing when it's done.

 - Consider fixed day buttons on scroll. 
 - Consider event detail view. Currently includes back link. Back button in header instead?
 - A few other notes on Invision mock-up.

**Comment by kristinashu** [comment]
Opening new ticket https://github.com/mozilla/schedule-app-core/issues/240
