### ISSUE TITLE
Optimize Search feature

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#192]
The search view could use a few improvements:
 - [ ] input placeholder text
 - [ ] dismiss button
 - [ ] input size, padding, border color
 - [ ] help text moved below the field (maybe only show when search input is empty)
 - [ ] initial state (an empty search should probably show no results. could show more bold help text)
 - [ ] and an optimized header #191

**Comment by kristinashu** [comment]
Closing and using https://github.com/mozilla/schedule-app-core/issues/244 instead.
