### ISSUE TITLE
Create event app requirement/estimation doc

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#221]
@xmatthewx and I had a conversation about event app requirements: http://etherpad.io/event-app-estimating (around line 45-85).

I'll 
- create a Google Doc that lists out all the requirements with my rough guess on time estimation
- share the doc with the team & flag people for their input

/cc @hannahkane @xmatthewx @acabunoc @cadecairos @kristinashu

**Comment by xmatthewx** [comment]
@mmmavis – can you drop a link here to your google doc? thanks!

**Comment by mmmavis** [comment]
here it is: https://docs.google.com/document/d/1qoIoUn66TsyrOS6MfDbHN_G-Q4j1mZQlMgtzhWN257g/edit# 🌻

**Comment by xmatthewx** [comment]
Thanks. @kristinashu to add design estimation.

**Comment by kristinashu** [comment]
I've add notes and estimates. 

I think this is good to close but please reopen if you think otherwise.
