### ISSUE TITLE
UI refresh

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#222]
Refresh the look of header, nav, plus other things (dependent on design)

**Comment by kristinashu** [comment]
Based on notes from London (https://public.etherpad-mozilla.org/p/mofolondon-mlnproductionbreakoutgroups), here are some potential improvements:
- Apply mofo universal design style to app
- Reduce scrolling length (on mobile especially)
- Preserve app state across app session
- Get feedback from staff on London use of pads
- Explore offline functionality
- Improve admin experience of session management
- Evaluate benefits of Reactivation?

**Comment by xmatthewx** [comment]
> Preserve app state across app session

Likely out of scope

> Get feedback from staff on London use of pads

I would just see if @edrushka wants to include links to etherpad

> Improve admin experience of session management

I would discuss with @edrushka in #238

**Comment by kristinashu** [comment]
Opened a bunch of tickets to deal with all of these separately https://github.com/mozilla/schedule-app-core/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2%2C+2016%22+label%3ADesign
