### ISSUE TITLE
Review estimates, plan roadmap

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#235]
Based on [estimation](https://github.com/mozilla/schedule-app-core/issues/221), we should evaluate options for iteration on event app in preparation for Mozfest based on resources. Then, set a roadmap. 

First step, schedule a meeting to review estimation.

**Comment by hannahkane** [comment]
Do we still need to do this?

**Comment by xmatthewx** [comment]
No? We should probably do estimates for the reduced scope to setup the app for mozfest with small set of easy wins. Meeting with @mmmavis and @kristinashu today for a pre-kickoff kickoff.

**Comment by kristinashu** [comment]
Mavis and I will do minimal work to the app. This heartbeat, I'll begin a light UI refresh integrating some of our universal design elements and will check with Mavis to identify easy wins. Mavis will begin setup of app instance for mozfest, triage a few bugs from the backlog, and plan upcoming work.

https://github.com/MozillaFoundation/Mozfest2016_production/issues/77
