### ISSUE TITLE
Header UI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#240]
Current app headers:

https://app.mozillafestival.org/#_show-saturday
http://mozilla.github.io/mofo-allhands/2016-london/#_show-tuesday

<img width="804" alt="screen shot 2016-08-22 at 12 53 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/17869284/74a82074-6867-11e6-8feb-530d17ccb92e.png">

Ricardo's did some work in https://github.com/mozilla/schedule-app-core/issues/191 comp https://invis.io/K774WYC4B#/155167007_Nav

<img width="377" alt="screen shot 2016-08-22 at 12 43 04 pm" src="https://cloud.githubusercontent.com/assets/1068783/17872017/0ab82cb6-6873-11e6-85f1-269bbcc11c27.png">

- header should be made more app like (DONE)
- remove intro text?
- remove 'tickets' link https://github.com/mozilla/schedule-app-core/issues/261
- might also be minified on scroll or on views that aren't the landing page
- consider fixed day buttons on scroll
- only show date picker when user is on "schedule" tab (hide on search, detail pages, spaces, pathways) https://github.com/mozilla/schedule-app-core/issues/268

**Comment by kristinashu** [comment]
@mmmavis is moving Search to the top header (like in Ricardo's comp above) doable in a 'reasonable' amount of time?

**Comment by mmmavis** [comment]
hey @kristinashu that depends on what happens when someone click on the search icon

**Comment by kristinashu** [comment]
@mmmavis here's one thought https://github.com/mozilla/schedule-app-core/issues/244 but let me know what would make it possible vs not possible and I can work around that.

**Comment by kristinashu** [comment]
@mmmavis sooooo what about also moving Favs to the top menu?

<img width="375" alt="screen shot 2016-08-25 at 1 42 47 pm" src="https://cloud.githubusercontent.com/assets/1068783/17985383/61d426a4-6aca-11e6-8a60-68486aec3274.png">

Realizing if we hide the date picker on all the screens (except for schedule landing screen) then users can't access their Favs the way they would expect to.
