### ISSUE TITLE
Search UI

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#244]
Currently:
https://app.mozillafestival.org/#_show-all
http://mozilla.github.io/mofo-allhands/2016-london/#_show-all

<img width="815" alt="screen shot 2016-08-22 at 12 51 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/17869654/20626c98-6869-11e6-859e-14cbc2a3ce14.png">

- remove " Show/hide descriptions" link text https://github.com/mozilla/schedule-app-core/issues/253 (DONE)
- hide cards until users starts typing https://github.com/mozilla/schedule-app-core/issues/255 (DONE)
- turn "Search names, facilitators, spaces, pathways .. " text into placeholder text #263 (DONE)
- dismiss button

Based on https://github.com/mozilla/schedule-app-core/issues/192
Some work Ricardo did:
<img width="375" alt="screen shot 2016-08-22 at 1 20 46 pm" src="https://cloud.githubusercontent.com/assets/1068783/17870218/5a59fb9e-686b-11e6-9075-7630093ff90b.png">

**Comment by kristinashu** [comment]
@mmmavis if we do 'Clicking logo links to landing screen' https://github.com/mozilla/schedule-app-core/issues/266 then we won't need the dismiss button. User would stay on search screen until they click on logo, Pathways, or Spaces links. 

This would avoid having to know which screen the user was on before they clicked search. Also, functionality would be more consistent with the other menu items like Spaces and Pathways.

**Comment by kristinashu** [comment]
Note on Ricardo's comp above: we won't need the search button since we're using live search.

**Comment by mmmavis** [comment]
Hey @kristinashu , I'm a bit lost now. 😁  I think the majority of the things mentioned here are done: https://mozilla.github.io/mozfest-schedule-app . Can you create new tickets for things I did not tackle? Thanks!

**Comment by kristinashu** [comment]
Looks good!
