### ISSUE TITLE
Show Back button and hide nav on 'third level' pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#246]
Current card detail view UI :
http://mozilla.github.io/mofo-allhands/2016-london/#_session-102
https://app.mozillafestival.org/#_session-100000

<img width="815" alt="screen shot 2016-08-22 at 1 24 21 pm" src="https://cloud.githubusercontent.com/assets/1068783/17870303/ccf49560-686b-11e6-8389-85cf30ded669.png">

Should just be:
<img width="856" alt="screen shot 2016-08-25 at 12 52 57 pm" src="https://cloud.githubusercontent.com/assets/1068783/17984571/aa0aa1a4-6ac6-11e6-9918-dc8fd7c6352a.png">

**Comment by kristinashu** [comment]
@mmmavis can we hid the nav (top header and days) and just show a the 'back to full schedule' button?
<img width="373" alt="screen shot 2016-08-22 at 2 56 58 pm" src="https://cloud.githubusercontent.com/assets/1068783/17873147/b81c9bb2-6878-11e6-95a3-d1edf93f4aa4.png">

**Comment by kristinashu** [comment]
We should also hide the nav and just show a back button when:
- user clicks on 'themes' then clicks on 'See all events in this theme'
- user clicks on 'tags' then clicks on one of them (ex Privacy) 
Those grid of sessions should only have a back button and no header.

Staging:
<img width="964" alt="screen shot 2016-08-25 at 11 59 33 am" src="https://cloud.githubusercontent.com/assets/1068783/17982249/ee17e95c-6abb-11e6-87a9-b1c07f3b169f.png">
<img width="1018" alt="screen shot 2016-08-25 at 11 59 46 am" src="https://cloud.githubusercontent.com/assets/1068783/17982250/ee1a5bec-6abb-11e6-9c07-1d287e9064e3.png">

**Comment by kristinashu** [comment]
Search needs this too: User clicks on 'search', types in a search term, then clicks on one of the results. The session detail view that they clicked on should just have a back button (no nav). The back button should return the user to the search screen (if possible, with their search term still entered)

**Comment by kristinashu** [comment]
@mmmavis the new condensed nav https://github.com/mozilla/schedule-app-core/issues/240 and removing the date picker https://github.com/mozilla/schedule-app-core/issues/268 might be enough. Lets hold off on this (unless you've already done it).

**Comment by kristinashu** [comment]
^ nevermind!

**Comment by mmmavis** [comment]
I think this is done: https://mozilla.github.io/mozfest-schedule-app . Free feel to open a new ticket if anything doesn't work as expected.
