### ISSUE TITLE
Brand UI: Align with unified design and 2016 branding

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#247]
Make some updated to align with mofo unified design.
Consider using mofo-bootstrap https://github.com/mozilla/schedule-app-core/issues/237
Update to 2016 colors https://github.com/mozilla/schedule-app-core/issues/267

**Comment by kristinashu** [comment]
@mmmavis I did a quick mockup of how the UI could look. Not saying we need to all of these changes but would like your thoughts on the direction:
- uses Fira to align with mofo unified design
- colors are not finalized but are closer to what 2016 will be https://github.com/mozilla/schedule-app-core/issues/267
- moved Favs to top menu https://github.com/mozilla/schedule-app-core/issues/271
- added "Schedule" link to menu (menu could be sticky - not including logo)
- reduced meta data https://github.com/mozilla/schedule-app-core/issues/258
- removed title (2016 MozFest Schedule, October 28-30, Ravensbourn, London) and incorporated info into other areas
- reduced scroll length (would want to see it, but if length is reduced enough then we would not need to have a collapsed view https://github.com/mozilla/schedule-app-core/issues/252 - but probably would still need it)

**Comment by kristinashu** [comment]
@mmmavis updated the mock: https://redpen.io/p/xy6a7fd8216decb98e
- uses Fira to align with mofo unified design
- colors are not finalized but are closer to what 2016 will be https://github.com/mozilla/schedule-app-core/issues/267
- added "Schedule" link to menu (menu could be sticky - not including logo)
- reduced meta data https://github.com/mozilla/schedule-app-core/issues/258
- reduced scroll length

Colors aren't final but the comps uses:
- purple #4632C3 
- light purple #BDB7E3
- teal #00FCDD 
- pink EB238B

Still need to figure out how to highlight things everyone should attend (alternative to red bar at the bottom of session thumbnail). 

Here's the sketch file: https://drive.google.com/open?id=0B2irLVDJivhLMTZtUjY5a1NBNDg
Note: Comp was done quite quickly and I haven't mocked up any of the other screens or a desktop version yet.

**Comment by kristinashu** [comment]
Opened https://github.com/mozilla/schedule-app-core/issues/288 and #289 for remaining things. I think we can close this?

**Comment by mmmavis** [comment]
🍻
