### ISSUE TITLE
Default view should be collapsed view (UX improvement)

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#252]
Sat and Sun has lots of sessions which makes for a lot of scrolling, we should collapse all the sessions so we only see the times. This way a user needs to click on a time to expand open all the sessions at that time.

Messy but could Friday be an exception? There is only one thing on on Friday so could that one be open? If not then that's ok.

Also, MozFest app has a "Hide all sessions" and "Show all sessions" (all hands app does not). We can remove this from the MozFest app.

cc @mmmavis

**Comment by mmmavis** [comment]
Let's not have an exception... since the same script is being used by other event app instances like the Allhands schedule app.

**Comment by kristinashu** [comment]
Yup, makes sense.
