### ISSUE TITLE
Session detail view: Add etherpad link

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#254]
Should the event app have the "Photos & Notes" link we used at london all-hand?

<img width="658" alt="screen shot 2016-08-24 at 1 52 26 pm" src="https://cloud.githubusercontent.com/assets/1068783/17947549/055ac20c-6a02-11e6-8018-da13a2a032d4.png">

**Comment by kristinashu** [comment]
@edrushka Matthew said it's up to you!

**Comment by edrushka** [comment]
@Saallen I say yes since this functionality exists.

**Comment by Saallen** [comment]
Yes please- we need a tool for people to upload notes and links pre and post session.

**Comment by kristinashu** [comment]
Ok, excellent! 

@mmmavis please keep the button link.

**Comment by mmmavis** [comment]
App should be able to display this already. See sample page: http://mozilla.github.io/mozfest-schedule-app/#_session-100
