### ISSUE TITLE
Space/Pathway: Space descriptions and Pathway descriptions

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#259]
Hi @edrushka and @Saallen 

Last year on the Space page of the event app we showed description of each Space: https://app.mozillafestival.org/#_spaces I wonder if this is something we'd like to do this year? If so can we just re-use the description from https://mozillafestival.org/spaces-and-sessions ?

Similar question for Pathways, do we have Pathways this year? If so, how many are they and where can we pull the description from? 🌞 

Also, @kristinashu and I were thinking to include some intro to the Space page and the Pathway page to help users understand the difference between Spaces and Pathways. Any thoughts on this?

**Comment by edrushka** [comment]
If it's already built in to display those descriptions, then yes, let's do that again this year. We can use descriptions from the Spaces and Sessions page, although be aware those might be edited slightly after the curation process is done (they were originally written in May, so have probably evolved). 

Same for pathways. We'll have *way* fewer pathways this year (hoping 10 or less). We're putting them together now - should be finished near end of September. We can give you descriptions then.

Feel free to give us a word limit for both the Space and Pathway descriptions.

**Comment by mmmavis** [comment]
@edrushka do we already know what Pathways there will be this year? Or is it still enter-your-own like what we had last year?

**Comment by edrushka** [comment]
We don't know yet. We'll have the list of 10 (or so) later in September.

**Comment by mmmavis** [comment]
My question got answered. Closing this ticket now. 🎉
