### ISSUE TITLE
Nav: Remove link to buy tickets

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#261]
@edrushka do we still want the link to buy tickets on the website or can we remove it? I would love to remove it since it's an external link and a little out of place but understand if we want to keep it to encourage ticket sales.

<img width="1279" alt="screen shot 2016-08-24 at 3 57 01 pm" src="https://cloud.githubusercontent.com/assets/1068783/17950964/7fe79ff2-6a13-11e6-8056-6d453d3870c9.png">

**Comment by edrushka** [comment]
You mean on the app, right? If so, yes, we can remove. Tickets sell out by the time the festival starts.

**Comment by kristinashu** [comment]
Ok, excellent! Yes, I mean on the app.

@mmmavis please remove the "Tickets" link.

**Comment by mmmavis** [comment]
this is already done, see "staging" https://mozilla.github.io/mozfest-schedule-app
