### ISSUE TITLE
Move Favs to top nav

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#271]
Realizing if we hide the date picker https://github.com/mozilla/schedule-app-core/issues/268 on all the screens (except for schedule landing screen) then users can't access their Favs the way they would expect to.

@mmmavis  would it be a big job to move the Favs to the top nav as well?

<img width="375" alt="screen shot 2016-08-25 at 1 42 47 pm" src="https://cloud.githubusercontent.com/assets/1068783/17987435/dc20860a-6ad4-11e6-84b8-bb14d2f2f674.png">

**Comment by mmmavis** [comment]
@kristinashu are we still doing this?

**Comment by kristinashu** [comment]
Nope!
