### ISSUE TITLE
Update colours for MozFest app

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#281]
colours are not final yet but for now let's just give the MozFest app a quick makeover 💄

**Comment by mmmavis** [comment]
quick makeover is done: https://mozilla.github.io/mozfest-schedule-app/

few notes:

- text seems small, especially on desktop.
- can we use font awesome for icons used in the project card? they are currently SVG so I wasn't able to change the colour to lighter grey
- I will need help to export a better logo SVG. I tried with Sketch but somehow the right edge got cut off 😬  
- Do we want to reduce the max width of the "container"? It's currently set to 768px.

/cc @kristinashu

**Comment by kristinashu** [comment]
Thanks @mmmavis!
- lets increase all fonts that are .875rem to 1rem
- svg of logo [logo-mozfest2016.svg.zip](https://github.com/mozilla/schedule-app-core/files/447942/logo-mozfest2016.svg.zip)
- font awesome icons: fa-clock-o [&#xf017;] and fa-map-marker [&#xf041;]
(for detail: fa-user [&#xf007;] and could use fa-map-signs [&#xf277;] for pathways)
- container max width seems good to me
