### ISSUE TITLE
Text alignment in timeblock divider

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#282]
@kristinashu Just a suggestion 😁 

In timeblock dividers, although the text label is positioned at center visually it doesn't look like so since some space in the right half is taken by the toggle button. I'm thinking maybe we can left align the text label instead? What do you think?

**So instead of this**

<img src="https://cloud.githubusercontent.com/assets/2896608/18070791/2c1933b8-6e05-11e6-946d-a1c8a2ddc1be.png" width="320">

---

**Can we left align the text?**

<img src="https://cloud.githubusercontent.com/assets/2896608/18070824/7241d48a-6e05-11e6-8995-9a4d814bdd77.png" width="320">

<img src="https://cloud.githubusercontent.com/assets/2896608/18070825/72477084-6e05-11e6-90a1-ae55c3b2f3cf.png" width="320">

**Comment by kristinashu** [comment]
@mmmavis sounds good to me, thanks!
