### ISSUE TITLE
[Proposal data related] How are pathways assigned?

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#286]
@edrushka @Saallen 

Proposals in https://github.com/MozillaFoundation/mozfest-program-2016/issues don't have pathways assigned currently. I'm wondering how and when we are planning to do that. Do we plan to have pre-defined `[Pathway ___]` labels and have program staff to assign them to the selected proposals after curation process is done?

**Comment by edrushka** [comment]
I think Sarah or I will probably end up assigning the pathways. This will be done after the curation finishes. Estimated date for assigning will be late September.

Estimating there will be around 10 pathways, with ~10-15 sessions per pathway.

**Comment by mmmavis** [comment]
Cool, that's good to know. 😄 This means when I export Github tickets to spreadsheet they should each have pathway info attached to them. Lovely!

**Comment by mmmavis** [comment]
Resolved.
