### ISSUE TITLE
Main nav tweeks

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#289]
Based on https://github.com/mozilla/schedule-app-core/issues/247
- add 'schedule' link (same as clicking logo but a little more obvious) 
- nav text and search icon light purple #BDB7E3 (instead of grey) with white selected and hover state (instead of underline)
- increase gap between 'Pathways' and the Search icon (so it is the same gap as in between 'Spaces' and 'Pathways' (sorry, @mmmavis I think you asked me about this in a ticket but I can't find it now)

**Comment by mmmavis** [comment]
Done!
