### ISSUE TITLE
Add 'no search results' text

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#290]
Add text below the search bar if the search turns up 0 results. Text can be the same as Pulse:
"Nothing found. Try another search or submit something new!"

**Comment by mmmavis** [comment]
Submit new doesn't really apply for MozFest schedule app. Is it okay that we just use "Nothing found. Try another search." ?

**Comment by kristinashu** [comment]
Ha good point! Lets go with:
Nothing found, please try another search.

**Comment by mmmavis** [comment]
okie dokie!
