### ISSUE TITLE
Session detail view styling

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#292]
I've mocked up a detail view: https://redpen.io/zmd1925bd09bcc9798

Summary of updates:
- add purple background bar around 'back'
- update text from 'back to full schedule' to 'back' (to be more flexible)
- put title and description in the white background box
- example button linking to etherpads (https://github.com/mozilla/schedule-app-core/issues/254)
- example text link in purple (https://github.com/mozilla/schedule-app-core/issues/291)

<img width="319" alt="screen shot 2016-08-31 at 11 51 07 am" src="https://cloud.githubusercontent.com/assets/1068783/18142181/3e8ecb58-6f71-11e6-9654-970a249e60c9.png">

**Comment by mmmavis** [comment]
Done!
