### ISSUE TITLE
consider changing "Back to full schedule" link text

### ISSUE THREAD

**Issue by ryanpitts** [mozilla/schedule-app-core#30]
After you open a session detail view, you get that nice "Back to full schedule" link at the top.

![screen shot 2015-10-29 at 9 32 22 pm](https://cloud.githubusercontent.com/assets/56477/10838510/a6e33178-7e84-11e5-80a6-01b6697cf1a3.png)

Clicking it tells the app to mimic a "back" in your browsing history, which doesn't _necessarily_ take you back to the "full" schedule. For example, if you've filtered your way into a pathway view, and then you open a session detail from there, clicking the "back" link will take you back out to that filtered pathway view.

Which is great! That's exactly the behavior you probably want as a user. But it means the "Back to full schedule" link text might be a little misleading. I'd propose editing to something like "Back to session list," which sounds a little more generic. @mmmavis any thoughts?

**Comment by mmmavis** [comment]
oh yea, i was gonna enter a ticket for this but i forgot!

I think we can just 
1) change the copy to "Back to previous view" or "Back to previous page"
2) just say "Back"
3) (open for suggestion) :smile: /cc @cassiemc

**Comment by ioana-chiorean** [comment]
If we make a decision, we need to confirm if we need a "Back to Full Schedule" button also? ( Maybe implemented in Right part)

**Comment by ryanpitts** [comment]
I *think* we are OK without an extra "full schedule" link, because the full schedule is always accessible by tapping any of the tabs above the list.

**Comment by mmmavis** [comment]
I think "Back to session list" will work better than "Back to full schedule" for sure :smile:

**Comment by cassiemc** [comment]
I like either just 'back' or, if that behavior isn't exactly true, 'Back to sessions'

**Comment by ryanpitts** [comment]
:+1: to "Back to sessions"

**Comment by mmmavis** [comment]
Closing this now. Marked this ticket as "MozFest 2015" in case we want to revisit again.
