### ISSUE TITLE
Design Pathways and Spaces screens

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#301]

**Comment by kristinashu** [comment]
Still working on it but I've mocked up these screens https://invis.io/ZU8H4AZS3#/185660141_Schedule_Landing

@mmmavis I've been doing some finessing and trying out a few little things. Can you please take a look? Let me know if you have any thoughts or we can chat in the office tomorrow.

**Comment by mmmavis** [comment]
Let's chat in the office later 😉

**Comment by mmmavis** [comment]
Design is done. Closing this ticket. 🍻
