### ISSUE TITLE
Design Search screen 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/schedule-app-core#302]
Minor style tweaks

**Comment by kristinashu** [comment]
@mmmavis I think the search screen should have the same nav as the other screens (instead of the cancel button). Would that be a pretty straight forward update to do?

<img width="316" alt="screen shot 2016-09-01 at 3 02 14 pm" src="https://cloud.githubusercontent.com/assets/1068783/18186006/1ccdeb54-7055-11e6-943a-a814dee5af6a.png">

**Comment by mmmavis** [comment]
Design is done and I've created an implementation ticket. Closing this one now! Wooohooo!
