### ISSUE TITLE
Editing the main stage sessions

### ISSUE THREAD

**Issue by thornet** [mozilla/schedule-app-core#31]
@mmmavis Where do we edit the main stage times and descriptions best? We'll likely have to do updates from now through the weekend.

**Comment by mmmavis** [comment]
@thornet through the "Main Stage" tab on the same Spreadsheet.  Let me know if you need help add more items to the time/location dropdown.

For "githubIssueNumber" I think it might be better to create a ticket on `mozfest-program` first to reserve the ID (as Ryan mentioned in the email).

**Comment by thornet** [comment]
@mmmavis thanks!

We added a few updated times in the spreadsheet. Mind taking a peek to see
if they work?

On Fri, Oct 30, 2015 at 6:07 PM, Mavis Ou <notifications@github.com> wrote:

> @thornet <https://github.com/thornet> through the "Main Stage" tab on the
> same Spreadsheet. Let me know if you need help add more items to the
> time/location dropdown.
>
> For "githubIssueNumber" I think it might be better to create a ticket on
> mozfest-program first to reserve the ID (as Ryan mentioned in the email).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/mozfest-schedule-app/issues/31#issuecomment-152604839>
> .
>



-- 
*Michelle Thorne*
Director, Mozilla Learning Programs
Mozilla Foundation

@thornet
michelle@mozillafoundation.org

**Comment by mmmavis** [comment]
Closing this now. Marked this ticket as "MozFest 2015" in case we want to revisit again.
