### ISSUE TITLE
Label Sunday with start time

### ISSUE THREAD

**Issue by cassiemc** [mozilla/schedule-app-core#48]
Not sure if this will be updated, but the "Saturday 9:00am" vs. "Sunday Opening Circle" headers leave me wondering what's different about Sunday? What's an opening circle? Are there not morning keynotes both days?

Maybe that will be clearer once they keynote sessions are input, but I think Sunday would still benefit from a start time.

**Comment by mmmavis** [comment]
Agree.  I wasn't sure when the start time was so I just put that as a placeholder.  Will check with @thornet on this.

**Comment by ryanpitts** [comment]
Fixing template in upcoming PR
