### ISSUE TITLE
Room / locations displaying in session titles

### ISSUE THREAD

**Issue by cassiemc** [mozilla/schedule-app-core#51]
Assuming this is a content / spreadsheet thing, but some sessions have their floor and room number displaying in the title rather than next to the location icon.

**Comment by mmmavis** [comment]
yup yup this is cuz the "location" column in the spreadsheet is hidden on some tabs still.  I entered a ticket for @thornet & @Saallen on this already: https://github.com/mozilla/mozfest-schedule-app/issues/47 :bowtie:

**Comment by mmmavis** [comment]
Closing this now. Marked this ticket as "MozFest 2015" in case we want to revisit again.
