### ISSUE TITLE
Tweaks for the "heart" icon

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#58]
feedback from yesterday's demo call

> Love the favorites feature, but think that the heart should go to the top right of the box instead of top left, because it seems like an icon for that talk instead of a UI element.
Another suggestion woudl be to add a small plus into the heart icon

What do you think @cassiemc @ryanpitts ? I like both ideas!

**Comment by cassiemc** [comment]
I like both ideas. Top right is a little easier on the thumb, and an addition of the plus icon makes it seem more like actionable UI.

**Comment by ryanpitts** [comment]
Yes :+1: to both ideas. I like the tap targets at right myself, but then again I am a right-hander :)

**Comment by mmmavis** [comment]
i can move the icon to the right side but will need help on creating the new "heart+" icon

**Comment by mmmavis** [comment]
updates: the heart icon have been relocated to the right side

**Comment by mmmavis** [comment]
Obsolete. Gonna close this ticket. :wink:
