### ISSUE TITLE
[BUG, MUST FIX] Clear appcache

### ISSUE THREAD

**Issue by mmmavis** [mozilla/schedule-app-core#85]
A lot of people are still seeing last year's schedule when they visit http://schedule.mozillafestival.org/.  Force refresh doesn't help.  It's probably the offline appcache that's causing the issue.

For reference, repo for last year's MozFest Schedule app is at: https://github.com/fuzzyfox/firehug 

@ryanpitts @fuzzyfox do you guys know a way to fix it?

/cc @jbuck @Pomax

**Comment by Pomax** [comment]
it looks like the old applicationCache is still around and even we set index.html to point to the same named applicationCache file, with an updated "empty" content, FF will not update it and load the new site on http. https is fine, but http is proving to be a pretty hardcore problem

**Comment by mmmavis** [comment]
and now https://schedule.mozillafestival.org/ looks like a plain html file to me (on Firefox only) :cry: 

<img width="482" alt="screen shot 2015-11-05 at 11 23 09 pm" src="https://cloud.githubusercontent.com/assets/2896608/10984842/438ccd2e-8414-11e5-8902-077ff9dd2d69.png">

**Comment by flamingspaz** [comment]
Had to double check this wasn't an issue with S3/CloudFront, it's definitely an appcache issue. firehug.appcache is the one currently in production, I think referencing it from the html has borked it somehow.

**Comment by acabunoc** [comment]
I'm also seeing this now:

![screen shot 2015-11-06 at 00 12 27](https://cloud.githubusercontent.com/assets/617994/10985663/16ee588a-841b-11e5-8e8f-37bd318bac4f.png)

**Comment by ScottDowne** [comment]
Just poking my head in, by wouldn't mozillafestival.org/schedule be a better url anyway?

**Comment by gbaman** [comment]
Yip, can confirm I am seeing the same on most platforms, bar for some odd reason with Chrome on IOS which is loading the schedule app, but with no data.

**Comment by mmmavis** [comment]
I just reverted Pomax's changes on `master` and hopefully that'll at least bring https://schedule.mozillafestival.org/ back ...

**Comment by mmmavis** [comment]
@ScottDowne helped me debug a bit but we couldn't find the fix either. Mike Hoye suggested that we should find httpd.conf / .htaccess in either in /etc/httpd/httpd.conf or (more likely) in .htaccess on the same folder where the file lives

I don't now where the Apache server for last year lives. @jbuck can you help?

**Comment by jbuck** [comment]
According to stackoverflow, the only reliable way to remove the appcache manifest is to link to a manifest that 404s (and change the current manifest): http://stackoverflow.com/questions/8815280/removing-html5-appcache-manifest-permanently

**Comment by Pomax** [comment]
not according to http://stackoverflow.com/a/31083156/740553 - firefox has bugs everywhere when it comes to appcache, and "how to clear" is one of them. The 404 solution is reliable in that it *doesn't* work, although setting the appcache to a "network: *" with "cache:" and "offline:" should force FF to no longer use AppCache. So we tried that! It did nothing either.

**Comment by mmmavis** [comment]
We have stopped using AppCache. Closing this ticket now. :+1:
