### ISSUE TITLE
Doesn't render in Chrome (canary?)

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/schedule-app-core#88]
Using chrome canary. Not sure why it looks like this. Tried hard refresh. Happening to a couple people.

<img width="1440" alt="screenshot 2015-11-06 10 04 14" src="https://cloud.githubusercontent.com/assets/403231/10994354/c06ea98a-846d-11e5-98ba-38013f683ad4.png">

**Comment by secretrobotron** [comment]
cc @samueledyson

**Comment by mmmavis** [comment]
Thanks for filing the bug @secretrobotron yay it's a known issue that we have been trying to fix :cry: 

for details refer to https://github.com/mozilla/mozfest-schedule-app/issues/85

**Comment by secretrobotron** [comment]
:+1: !!

**Comment by mmmavis** [comment]
Closing this now. Marked this ticket as "MozFest 2015" in case we want to revisit again.
